import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: {
        backgroundColor: '#FFFFFF',
        flex: 1,
    },
    keyboardView: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
    },
    screen: {
        alignSelf: 'center',
        flexGrow: 1,
        maxWidth: 560,
        paddingBottom: 28,
        paddingHorizontal: 20,
        width: '100%',
    },
    header: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        minHeight: 52,
    },
    backButton: {
        alignItems: 'center',
        borderRadius: 8,
        justifyContent: 'center',
        minHeight: 44,
        paddingHorizontal: 8,
    },
    backButtonPressed: {
        backgroundColor: '#F2EEF8',
    },
    backButtonText: {
        color: '#57418D',
        fontSize: 15,
        fontWeight: '600',
    },
    trackerTitle: {
        color: '#342E3A',
        fontSize: 14,
        fontWeight: '700',
    },
    assessmentTitle: {
        color: '#17151B',
        fontSize: 24,
        fontWeight: '700',
        lineHeight: 32,
        marginBottom: 14,
        marginTop: 8,
    },
    questionCard: {
        backgroundColor: '#FFFFFF',
        borderColor: '#DDD5E5',
        borderRadius: 14,
        borderWidth: 1,
        minHeight: 516,
        padding: 18,
    },
    sectionTitle: {
        color: '#342E3A',
        fontSize: 17,
        fontWeight: '600',
        lineHeight: 24,
    },
    divider: {
        backgroundColor: '#E7E0EB',
        height: 1,
        marginBottom: 18,
        marginTop: 12,
    },
    prompt: {
        color: '#342E3A',
        fontSize: 15,
        fontWeight: '600',
        lineHeight: 22,
    },
    promptUnderline: {
        textDecorationLine: 'underline',
    },
    helper: {
        color: '#6A646E',
        fontSize: 13,
        fontStyle: 'italic',
        lineHeight: 19,
        marginTop: 4,
    },
    optionsScroll: {
        backgroundColor: '#FCF9FD',
        borderRadius: 8,
        height: 390,
        marginTop: 14,
    },
    options: {
        paddingHorizontal: 4,
    },
    option: {
        alignItems: 'center',
        borderBottomColor: '#EEE9F1',
        borderBottomWidth: 1,
        flexDirection: 'row',
        minHeight: 56,
        paddingHorizontal: 4,
    },
    optionPressed: {
        backgroundColor: '#F7F3FA',
    },
    checkbox: {
        alignItems: 'center',
        borderColor: '#756C7C',
        borderRadius: 3,
        borderWidth: 1.5,
        height: 20,
        justifyContent: 'center',
        marginLeft: 'auto',
        pointerEvents: 'none',
        width: 20,
    },
    checkboxSelected: {
        backgroundColor: '#6D50AC',
        borderColor: '#6D50AC',
    },
    checkmark: {
        color: '#FFFFFF',
        fontSize: 13,
        fontWeight: '700',
        lineHeight: 16,
    },
    selectorOuter: {
        alignItems: 'center',
        height: 40,
        justifyContent: 'center',
        marginRight: 12,
        width: 40,
    },
    radioOuter: {
        alignItems: 'center',
        borderColor: '#756C7C',
        borderRadius: 12,
        borderWidth: 1.5,
        height: 24,
        justifyContent: 'center',
        width: 24,
    },
    radioOuterSelected: {
        borderColor: '#6D50AC',
    },
    radioDot: {
        backgroundColor: '#6D50AC',
        borderRadius: 6,
        height: 12,
        width: 12,
    },
    optionText: {
        color: '#342E3A',
        flex: 1,
        fontSize: 14,
        lineHeight: 20,
        paddingRight: 16,
    },
    optionTextSelected: {
        color: '#57418D',
        fontWeight: '600',
    },
    actionRow: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 18,
    },
    stepBadge: {
        alignItems: 'center',
        borderColor: '#D8CEE1',
        borderRadius: 10,
        borderWidth: 1,
        justifyContent: 'center',
        minHeight: 36,
        minWidth: 52,
        paddingHorizontal: 10,
    },
    stepText: {
        color: '#574F5D',
        fontSize: 13,
        fontWeight: '600',
    },
    recordButton: {
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderColor: '#D8CEE1',
        borderRadius: 15,
        borderWidth: 1.5,
        justifyContent: 'center',
        minHeight: 30,
        minWidth: 105,
        paddingHorizontal: 18,
    },
    recordButtonDisabled: {
        backgroundColor: '#E7D8FF',
    },
    recordButtonPressed: {
        opacity: 0.82,
    },
    recordButtonText: {
        color: '#574F5D',
        fontSize: 14,
        fontWeight: '600',
    },
    recordButtonTextDisabled: {
        color: '#554766',
    },
    modalInput: {
        backgroundColor: '#FCF9FD',
        borderColor: '#DDD5E5',
        borderRadius: 8,
        borderWidth: 1,
        color: '#17151B',
        fontSize: 15,
        height: 80,
        marginTop: 14,
        padding: 14,
        textAlignVertical: 'top',
    },
    summarySection: {
        borderBottomColor: '#EEE9F1',
        borderBottomWidth: 1,
        paddingVertical: 16,
    },
    summarySectionTitle: {
        color: '#342E3A',
        fontSize: 15,
        fontWeight: '700',
        lineHeight: 22,
    },
    summaryPeriod: {
        color: '#342E3A',
        fontSize: 13,
        fontWeight: '700',
    },
    summaryText: {
        color: '#4F4B55',
        fontSize: 14,
        lineHeight: 21,
        marginTop: 6,
    },
    summaryItem: {
        color: '#4F4B55',
        fontSize: 14,
        lineHeight: 22,
        marginTop: 4,
    },
    summaryValue: {
        fontWeight: '700',
    },
    summaryFooter: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
    },
    sessionNote: {
        color: '#6A646E',
        flex: 1,
        fontSize: 12,
        marginRight: 12,
    },
    summaryCloseButton: {
        backgroundColor: '#FFFFFF',
        borderColor: '#D8CEE1',
        borderWidth: 1,
    },
    summaryCloseButtonText: {
        color: '#57418D',
    },
    summaryHighlightBox: {
        backgroundColor: '#F1EDF4',
        borderRadius: 10,
        marginTop: 10,
        padding: 14,
    },
    summaryHighlightText: {
        color: '#342E3A',
        fontSize: 14,
        lineHeight: 21,
        textAlign: 'center',
    },
    summaryHighlightBold: {
        fontWeight: '700',
    },
    exploreTipsButton: {
        alignItems: 'center',
        backgroundColor: '#E7DFF2',
        borderRadius: 8,
        marginTop: 12,
        minHeight: 40,
        justifyContent: 'center',
    },
    exploreTipsText: {
        color: '#57418D',
        fontSize: 13,
        fontWeight: '600',
    },
});