import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  viewport: { alignSelf: 'center', backgroundColor: '#FFFFFF', flex: 1, width: '100%' },
  webViewport: { maxWidth: 390 },
  keyboard: { flex: 1 },
  header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 18, gap: 14 },
  title: { color: '#17151B', fontSize: 22, fontWeight: '700', lineHeight: 28 },
  subtitle: { color: '#4F4B55', fontSize: 14, lineHeight: 21 },
  titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  backButton: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 6, minHeight: 44 },
  backText: { color: '#51465F', fontSize: 15 },
  scroll: { flex: 1 },
  content: { paddingHorizontal: 20, paddingBottom: 24, flexGrow: 1, gap: 16 },
  card: { backgroundColor: '#F4F2F8', borderRadius: 14, padding: 18, gap: 14 },
  cardTitle: { color: '#17151B', fontSize: 17, fontWeight: '600', lineHeight: 24 },
  divider: { borderBottomColor: '#D8D1DE', borderBottomWidth: 1 },
  row: { flexDirection: 'row', gap: 12 },
  column: { flex: 1, gap: 8 },
  label: { color: '#38313F', fontSize: 13, fontWeight: '600', lineHeight: 18 },
  value: { color: '#17151B', fontSize: 14, lineHeight: 21 },
  result: { gap: 5 },
  muted: { color: '#716979', fontSize: 12, lineHeight: 18 },
  sessionNote: { color: '#716979', fontSize: 12, lineHeight: 18, marginTop: 6 },
  primaryButton: { backgroundColor: '#6850A1', borderRadius: 24, minHeight: 48, paddingHorizontal: 20, paddingVertical: 12, justifyContent: 'center', alignItems: 'center' },
  primaryText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600', textAlign: 'center' },
  secondaryButton: { backgroundColor: '#F4F2F8', borderRadius: 14, minHeight: 48, padding: 14, justifyContent: 'center', alignItems: 'center' },
  secondaryText: { color: '#362945', fontSize: 14, fontWeight: '600', textAlign: 'center', lineHeight: 20 },
  outlineButton: { borderColor: '#CFC5DA', borderWidth: 1, borderRadius: 22, minHeight: 44, paddingHorizontal: 16, paddingVertical: 10, alignItems: 'center', justifyContent: 'center' },
  outlineText: { color: '#4D3A67', fontSize: 13, fontWeight: '600' },
  alignEnd: { alignSelf: 'flex-end' },
  pressed: { opacity: 0.7 },
  disabled: { opacity: 0.4 },
  empty: { flex: 1, minHeight: 270, alignItems: 'center', justifyContent: 'center', gap: 18, padding: 16 },
  emptyTitle: { color: '#77717D', fontSize: 16, lineHeight: 24, textAlign: 'center' },
  centered: { textAlign: 'center' },
  footer: { paddingHorizontal: 20, paddingVertical: 12, backgroundColor: '#FFFFFF' },
  prescriptionList: { borderColor: '#D2CBD8', borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, flexGrow: 1 },
  prescriptionRow: { flexDirection: 'row', alignItems: 'center', borderBottomColor: '#E0DAE7', borderBottomWidth: 1, paddingVertical: 14, gap: 4 },
  prescriptionText: { flex: 1, gap: 5 },
  iconButton: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  deleteText: { color: '#AE283D', fontSize: 14, fontWeight: '600' },
  input: { backgroundColor: '#FCF8FF', borderColor: '#BDB3C8', borderWidth: 1, borderRadius: 6, color: '#17151B', fontSize: 15, minHeight: 48, paddingHorizontal: 12, paddingVertical: 12 },
  selectButton: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  field: { gap: 8 },
  formSection: { marginTop: 10, gap: 18 },
  modalBackdrop: { flex: 1, justifyContent: 'center', backgroundColor: '#17151B66', padding: 24 },
  modalCard: { backgroundColor: '#FFFFFF', borderRadius: 18, maxHeight: '80%', padding: 20, gap: 12, width: '100%', maxWidth: 390, alignSelf: 'center' },
  option: { minHeight: 48, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 12, borderRadius: 8 },
  selectedOption: { backgroundColor: '#ECE2FF' },
  tabs: { flexDirection: 'row', backgroundColor: '#FBF6FF', borderBottomColor: '#E0DAE7', borderBottomWidth: 1 },
  tab: { flex: 1, paddingVertical: 14, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  activeTab: { borderBottomColor: '#7554B8' },
  tabText: { color: '#4F4B55', fontSize: 14 },
  activeTabText: { color: '#6846A4', fontWeight: '600' },
  metricTabs: { flexDirection: 'row', borderWidth: 1, borderColor: '#D8D1DE', borderRadius: 22, overflow: 'hidden' },
  metricTab: { flex: 1, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  metricSelected: { backgroundColor: '#EADDFF' },
  table: { borderColor: '#D8D1DE', borderWidth: 1 },
  tableRow: { flexDirection: 'row', minHeight: 44, borderBottomColor: '#E0DAE7', borderBottomWidth: 1, alignItems: 'center' },
  tableDate: { flex: 1.5, padding: 8, fontSize: 11, color: '#4F4B55' },
  tableCell: { flex: 1, textAlign: 'center', paddingVertical: 8, fontSize: 12, color: '#17151B' },
  toast: { backgroundColor: '#EADDFF', borderRadius: 10, padding: 12 },
  weekButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 52, paddingVertical: 12 },
  historyRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, borderTopColor: '#DED7E7', borderTopWidth: 1, paddingVertical: 16 },
  error: { color: '#AE283D', fontSize: 13, lineHeight: 19 },
  exportRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
});
