import { colors, fonts } from '@/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  content: {
    alignItems: 'center',
    minHeight: 680,
    paddingTop: 72,
    width: '100%',
  },
  title: {
    fontFamily: fonts.display,
    letterSpacing: -0.5,
    color: colors.ink,
    fontSize: 26,
    fontWeight: '400',
    lineHeight: 32,
    maxWidth: 330,
    textAlign: 'center',
  },
  diagnosisOptions: {
    gap: 20,
    marginTop: 42,
    width: 238,
  },
  diagnosisOption: {
    alignItems: 'center',
    backgroundColor: colors.sky,
    borderBottomColor: colors.primary,
    borderBottomWidth: 1,
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
  },
  diagnosisOptionSelected: {
    backgroundColor: colors.primary,
    borderBottomColor: colors.primary,
  },
  optionPressed: {
    opacity: 0.82,
  },
  diagnosisOptionText: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: '600',
  },
  diagnosisOptionTextSelected: {
    color: colors.surface,
  },
  information: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 45,
    maxWidth: 290,
    textAlign: 'center',
  },
  primaryButton: {
    minHeight: 48,
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 12,
    height: 52,
    justifyContent: 'center',
    marginTop: 34,
    maxWidth: 282,
    width: '100%',
  },
  primaryButtonDisabled: {
    backgroundColor: colors.sky,
  },
  primaryButtonPressed: {
    opacity: 0.82,
  },
  primaryButtonText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '600',
  },
  primaryButtonTextDisabled: {
    color: colors.muted,
  },
  selectionContent: {
    paddingTop: 54,
  },
  selectionHelper: {
    color: colors.muted,
    fontSize: 14,
    marginTop: 16,
    textAlign: 'center',
  },
  searchContainer: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderBottomColor: colors.muted,
    borderBottomWidth: 1,
    flexDirection: 'row',
    height: 48,
    marginTop: 28,
    maxWidth: 282,
    paddingLeft: 16,
    width: '100%',
  },
  searchInput: {
    color: colors.ink,
    flex: 1,
    fontSize: 15,
    height: '100%',
    paddingRight: 8,
  },
  clearSearchButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  clearSearchButtonPressed: {
    backgroundColor: colors.border,
  },
  clearSearchText: {
    color: colors.primary,
    fontSize: 24,
    lineHeight: 26,
  },
  conditionsList: {
    borderColor: colors.border,
    borderWidth: 1,
    height: 310,
    marginTop: 14,
    maxWidth: 282,
    width: '100%',
  },
  conditionsListContent: {
    paddingBottom: 1,
  },
  conditionOption: {
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  conditionOptionSelected: {
    backgroundColor: colors.primary,
  },
  conditionOptionText: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 20,
  },
  conditionOptionTextSelected: {
    color: colors.surface,
    fontWeight: '600',
  },
  noResults: {
    color: colors.muted,
    fontSize: 14,
    paddingHorizontal: 16,
    paddingVertical: 24,
    textAlign: 'center',
  },
  selectionButton: {
    marginTop: 26,
  },
  skipButton: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 44,
    paddingHorizontal: 18,
  },
  skipButtonPressed: {
    backgroundColor: colors.sky,
  },
  skipButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  otherContent: {
    paddingTop: 102,
  },
  otherInput: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderBottomColor: colors.muted,
    borderBottomWidth: 1,
    color: colors.ink,
    fontSize: 15,
    height: 132,
    marginTop: 46,
    maxWidth: 282,
    padding: 16,
    textAlignVertical: 'top',
    width: '100%',
  },
  otherButton: {
    marginTop: 52,
  },
});
