import { colors, fonts } from '@/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  content: {
    alignItems: 'center',
    minHeight: 680,
    width: '100%',
  },
  introContent: {
    paddingTop: 142,
  },
  introTitle: {
    fontFamily: fonts.display,
    letterSpacing: -0.5,
    color: colors.ink,
    fontSize: 32,
    fontWeight: '400',
    lineHeight: 38,
    maxWidth: 310,
    textAlign: 'center',
  },
  introMessage: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 30,
    marginTop: 46,
    maxWidth: 300,
    textAlign: 'left',
  },
  primaryButton: {
    minHeight: 48,
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 12,
    height: 52,
    justifyContent: 'center',
    maxWidth: 282,
    width: '100%',
  },
  primaryButtonDisabled: {
    backgroundColor: colors.sky,
  },
  primaryButtonPressed: {
    opacity: 0.82,
  },
  primaryButtonText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '600',
  },
  primaryButtonTextDisabled: {
    color: colors.muted,
  },
  introButton: {
    marginTop: 56,
  },
  phoneContent: {
    paddingTop: 130,
  },
  title: {
    fontFamily: fonts.display,
    letterSpacing: -0.5,
    color: colors.ink,
    fontSize: 32,
    fontWeight: '400',
    lineHeight: 38,
    maxWidth: 310,
    textAlign: 'center',
  },
  phoneInput: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderBottomColor: colors.muted,
    borderBottomWidth: 1,
    color: colors.ink,
    fontSize: 18,
    height: 58,
    marginTop: 40,
    maxWidth: 282,
    paddingHorizontal: 16,
    textAlign: 'center',
    width: '100%',
  },
  phoneHelper: {
    color: colors.ink,
    fontSize: 16,
    lineHeight: 23,
    marginTop: 44,
    maxWidth: 270,
    textAlign: 'center',
  },
  phoneButton: {
    marginTop: 84,
  },
  verificationContent: {
    paddingTop: 104,
  },
  verificationTitle: {
    fontFamily: fonts.display,
    letterSpacing: -0.5,
    alignSelf: 'center',
    color: colors.ink,
    fontSize: 32,
    fontWeight: '400',
    lineHeight: 38,
    maxWidth: 282,
    textAlign: 'left',
    width: '100%',
  },
  codeInputArea: {
    height: 58,
    marginTop: 62,
    maxWidth: 282,
    position: 'relative',
    width: '100%',
  },
  codeBoxes: {
    flexDirection: 'row',
    gap: 12,
    height: 58,
    justifyContent: 'center',
    pointerEvents: 'none',
  },
  codeBox: {
    alignItems: 'center',
    backgroundColor: colors.sky,
    borderColor: colors.muted,
    borderRadius: 7,
    borderWidth: 1,
    height: 58,
    justifyContent: 'center',
    width: 54,
  },
  codeBoxActive: {
    borderColor: colors.primary,
    borderWidth: 2,
  },
  codeDigit: {
    color: colors.ink,
    fontSize: 22,
    fontWeight: '600',
  },
  codeInput: {
    color: 'transparent',
    height: 58,
    left: 0,
    opacity: 0.02,
    position: 'absolute',
    top: 0,
    width: '100%',
  },
  resendButton: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 26,
    minHeight: 40,
    paddingHorizontal: 12,
  },
  resendButtonPressed: {
    backgroundColor: colors.sky,
  },
  resendButtonText: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  resendButtonTextDisabled: {
    color: colors.muted,
  },
  resendHelper: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 2,
    textAlign: 'center',
  },
  verifyButton: {
    marginTop: 68,
  },
});
