import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    viewport: { alignSelf: 'center', backgroundColor: '#FFFFFF', flex: 1, width: '100%' },
    webViewport: { maxWidth: 390 },
    keyboard: { flex: 1 },
    header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 18, gap: 14 },
    title: { color: '#17151B', fontSize: 22, fontWeight: '700', lineHeight: 28 },
    subtitle: { color: '#4F4B55', fontSize: 14, lineHeight: 21 },
    backButton: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 6, minHeight: 44 },
    backText: { color: '#51465F', fontSize: 15 },
    scroll: { flex: 1 },
    content: { paddingHorizontal: 20, paddingBottom: 24, flexGrow: 1, gap: 16 },
    card: { backgroundColor: '#F4F2F8', borderRadius: 14, padding: 18, gap: 14 },
    cardButtonText: { color: '#4D3A67', fontSize: 14, fontWeight: '600', lineHeight: 20 },
    previewTitle: { color: '#17151B', fontSize: 18, fontWeight: '700', lineHeight: 25 },
    label: { color: '#38313F', fontSize: 13, fontWeight: '600', lineHeight: 18 },
    value: { color: '#17151B', fontSize: 14, lineHeight: 21 },
    muted: { color: '#716979', fontSize: 12, lineHeight: 18 },
    disabled: { opacity: 0.4 },
    input: { backgroundColor: '#FCF8FF', borderColor: '#BDB3C8', borderWidth: 1, borderRadius: 6, color: '#17151B', fontSize: 15, minHeight: 48, paddingHorizontal: 12, paddingVertical: 12 },
    field: { gap: 8 },
    error: { color: '#AE283D', fontSize: 13, lineHeight: 19 },
    row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 56, paddingVertical: 14, paddingHorizontal: 4, borderBottomColor: '#E0DAE7', borderBottomWidth: 1 },
    rowText: { color: '#17151B', fontSize: 15, fontWeight: '600' },
    deleteText: { color: '#AE283D', fontSize: 13, fontWeight: '600' },
    logoutText: { color: '#AE283D', fontSize: 15, fontWeight: '600', textAlign: 'center', marginTop: 24, minHeight: 44, textAlignVertical: 'center' },
    codeInputArea: { height: 58, marginTop: 24, maxWidth: 282, position: 'relative', width: '100%', alignSelf: 'center' },
    codeBoxes: { flexDirection: 'row', gap: 12, height: 58, justifyContent: 'center', pointerEvents: 'none' },
    codeBox: { alignItems: 'center', backgroundColor: '#EAE6EF', borderColor: '#7A747D', borderRadius: 7, borderWidth: 1, height: 58, justifyContent: 'center', width: 54 },
    codeBoxActive: { borderColor: '#6D50AC', borderWidth: 2 },
    codeDigit: { color: '#17151B', fontSize: 22, fontWeight: '600' },
    codeInput: { color: 'transparent', height: 58, left: 0, opacity: 0.02, position: 'absolute', top: 0, width: '100%' },
    assessmentCard: { backgroundColor: '#F4F2F8', borderRadius: 14, padding: 12, gap: 10 },
    assessmentRow: { backgroundColor: '#FFFFFF', borderRadius: 12, minHeight: 56, justifyContent: 'center', paddingHorizontal: 16 },
    assessmentRowText: { color: '#17151B', fontSize: 15, fontWeight: '700' },
    greeting: { color: '#17151B', fontSize: 18, fontWeight: '700', marginBottom: 8 },
});
