import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    viewport: { alignSelf: 'center', backgroundColor: '#FFFFFF', flex: 1, width: '100%' },
    webViewport: { maxWidth: 390 },
    keyboard: { flex: 1 },
    header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 18, gap: 14 },
    title: { color: '#17151B', fontSize: 22, fontWeight: '700', lineHeight: 28 },
    subtitle: { color: '#4F4B55', fontSize: 14, lineHeight: 21 },
    titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
    backButton: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 6, minHeight: 44 },
    backText: { color: '#51465F', fontSize: 15 },
    scroll: { flex: 1 },
    content: { paddingHorizontal: 20, paddingBottom: 24, flexGrow: 1, gap: 16 },
    card: { backgroundColor: '#F4F2F8', borderRadius: 14, padding: 18, gap: 14 },
    cardTitle: { color: '#17151B', fontSize: 17, fontWeight: '600', lineHeight: 24 },
    divider: { borderBottomColor: '#D8D1DE', borderBottomWidth: 1 },
    cardButton: { alignItems: 'center', backgroundColor: '#FFFFFF', borderColor: '#CFC5DA', borderRadius: 24, borderWidth: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 20 },
    cardButtonText: { color: '#4D3A67', fontSize: 15, fontWeight: '600' },    column: { flex: 1, gap: 8 },
    label: { color: '#38313F', fontSize: 13, fontWeight: '600', lineHeight: 18 },
    value: { color: '#17151B', fontSize: 14, lineHeight: 21 },
    result: { gap: 5 },
    muted: { color: '#716979', fontSize: 12, lineHeight: 18 },
    sessionNote: { color: '#716979', fontSize: 12, lineHeight: 18, marginTop: 6 },
    primaryButton: { backgroundColor: '#6850A1', borderRadius: 24, minHeight: 48, paddingHorizontal: 20, paddingVertical: 12, justifyContent: 'center', alignItems: 'center' },
    primaryText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600', textAlign: 'center' },
    secondaryButton: { backgroundColor: '#F4F2F8', borderRadius: 14, minHeight: 48, padding: 14, justifyContent: 'center', alignItems: 'center' },
    secondaryText: { color: '#362945', fontSize: 14, fontWeight: '600', textAlign: 'center', lineHeight: 20 },
    outlineButton: { borderColor: '#CFC5DA', borderWidth: 1, borderRadius: 22, minHeight: 44, paddingHorizontal: 16, paddingVertical: 10, alignItems: 'center', justifyContent: 'center' },
    outlineText: { color: '#4D3A67', fontSize: 13, fontWeight: '600' },
    alignEnd: { alignSelf: 'flex-end' },
    pressed: { opacity: 0.7 },
    disabled: { opacity: 0.4 },
    input: { backgroundColor: '#FCF8FF', borderColor: '#BDB3C8', borderWidth: 1, borderRadius: 6, color: '#17151B', fontSize: 15, minHeight: 48, paddingHorizontal: 12, paddingVertical: 12 },
    field: { gap: 8 },
    formSection: { marginTop: 10, gap: 18 },
    error: { color: '#AE283D', fontSize: 13, lineHeight: 19 },
    row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 56, paddingVertical: 14, paddingHorizontal: 4, borderBottomColor: '#E0DAE7', borderBottomWidth: 1 },
    rowText: { color: '#17151B', fontSize: 15, fontWeight: '600' },
    deleteText: { color: '#AE283D', fontSize: 13, fontWeight: '600' },
    logoutText: { color: '#AE283D', fontSize: 15, fontWeight: '600', textAlign: 'center', marginTop: 24, minHeight: 44, textAlignVertical: 'center' },
});