import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  screen: {
    alignSelf: 'center',
    flexGrow: 1,
    maxWidth: 560,
    paddingBottom: 28,
    paddingHorizontal: 20,
    width: '100%',
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 52,
  },
  backButton: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 8,
  },
  backButtonPressed: {
    backgroundColor: '#F2EEF8',
  },
  backButtonText: {
    color: '#57418D',
    fontSize: 15,
    fontWeight: '600',
  },
  trackerTitle: {
    color: '#342E3A',
    fontSize: 14,
    fontWeight: '700',
  },
  assessmentTitle: {
    color: '#17151B',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 32,
    marginBottom: 14,
    marginTop: 8,
  },
  questionCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DDD5E5',
    borderRadius: 14,
    borderWidth: 1,
    padding: 18,
  },
  sectionTitle: {
    color: '#342E3A',
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 24,
  },
  divider: {
    backgroundColor: '#E7E0EB',
    height: 1,
    marginBottom: 18,
    marginTop: 12,
  },
  prompt: {
    color: '#342E3A',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
  },
  helper: {
    color: '#6A646E',
    fontSize: 13,
    fontStyle: 'italic',
    lineHeight: 19,
    marginTop: 8,
  },
  sourceLabel: {
    color: '#342E3A',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    marginTop: 16,
  },
  medicationList: {
    backgroundColor: '#FCF9FD',
    borderRadius: 8,
    maxHeight: 310,
    marginTop: 12,
  },
  medicationOption: {
    alignItems: 'center',
    borderBottomColor: '#E7E0EB',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 62,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  optionPressed: {
    backgroundColor: '#F2EEF8',
  },
  medicationTextGroup: {
    flex: 1,
    paddingRight: 14,
  },
  medicationName: {
    color: '#342E3A',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  medicationSchedule: {
    color: '#6A646E',
    fontSize: 12,
    lineHeight: 18,
  },
  checkbox: {
    alignItems: 'center',
    borderColor: '#756C7C',
    borderRadius: 3,
    borderWidth: 1.5,
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  checkboxSelected: {
    backgroundColor: '#6D50AC',
    borderColor: '#6D50AC',
  },
  checkmark: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 16,
  },
  textArea: {
    borderColor: '#DDD5E5',
    borderRadius: 10,
    borderWidth: 1,
    color: '#17151B',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 18,
    minHeight: 170,
    padding: 14,
    textAlignVertical: 'top',
  },
  choiceList: {
    backgroundColor: '#FCF9FD',
    borderRadius: 8,
    marginTop: 18,
  },
  choiceOption: {
    alignItems: 'center',
    borderBottomColor: '#E7E0EB',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 54,
    paddingHorizontal: 12,
  },
  radio: {
    alignItems: 'center',
    borderColor: '#756C7C',
    borderRadius: 10,
    borderWidth: 1.5,
    height: 20,
    justifyContent: 'center',
    marginRight: 14,
    width: 20,
  },
  radioSelected: {
    borderColor: '#6D50AC',
  },
  radioDot: {
    backgroundColor: '#6D50AC',
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  choiceLabel: {
    color: '#342E3A',
    fontSize: 14,
    fontWeight: '600',
  },
  actionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
  },
  stepBadge: {
    alignItems: 'center',
    borderColor: '#D8CEE1',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    minWidth: 52,
    paddingHorizontal: 10,
  },
  stepText: {
    color: '#574F5D',
    fontSize: 13,
    fontWeight: '600',
  },
  recordButton: {
    alignItems: 'center',
    backgroundColor: '#6D50AC',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 112,
    paddingHorizontal: 18,
  },
  recordButtonDisabled: {
    backgroundColor: '#E7D8FF',
  },
  recordButtonPressed: {
    opacity: 0.82,
  },
  recordButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  recordButtonTextDisabled: {
    color: '#554766',
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DDD5E5',
    borderRadius: 14,
    borderWidth: 1,
    padding: 18,
  },
  summaryTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  summaryPeriod: {
    color: '#342E3A',
    fontSize: 12,
    fontWeight: '700',
  },
  summarySectionTitle: {
    color: '#342E3A',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
  },
  overviewPanel: {
    backgroundColor: '#F5F2F8',
    borderRadius: 10,
    marginTop: 14,
    overflow: 'hidden',
  },
  overviewText: {
    color: '#342E3A',
    fontSize: 14,
    lineHeight: 21,
    padding: 16,
  },
  tipsButton: {
    alignItems: 'center',
    backgroundColor: '#D9D5DC',
    minHeight: 44,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  tipsButtonPressed: {
    opacity: 0.75,
  },
  tipsButtonText: {
    color: '#342E3A',
    fontSize: 13,
    fontWeight: '700',
  },
  resultGroup: {
    marginTop: 18,
  },
  resultLabel: {
    color: '#342E3A',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 21,
  },
  resultText: {
    color: '#4F4B55',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 4,
  },
  summaryFooter: {
    alignItems: 'center',
    borderTopColor: '#E7E0EB',
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 22,
    paddingTop: 16,
  },
  journalStatus: {
    color: '#6A646E',
    flex: 1,
    fontSize: 12,
    marginRight: 12,
  },
  closeButton: {
    alignItems: 'center',
    borderColor: '#D8CEE1',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    minWidth: 100,
    paddingHorizontal: 16,
  },
  closeButtonPressed: {
    backgroundColor: '#F2EEF8',
  },
  closeButtonText: {
    color: '#57418D',
    fontSize: 14,
    fontWeight: '600',
  },
});
