import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  screen: {
    alignSelf: 'center',
    flexGrow: 1,
    maxWidth: 560,
    paddingBottom: 28,
    paddingHorizontal: 20,
    width: '100%',
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 52,
  },
  backButton: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 8,
  },
  backButtonPressed: {
    backgroundColor: '#F2EEF8',
  },
  backButtonText: {
    color: '#57418D',
    fontSize: 15,
    fontWeight: '600',
  },
  trackerTitle: {
    color: '#342E3A',
    fontSize: 14,
    fontWeight: '700',
  },
  assessmentTitle: {
    color: '#17151B',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 32,
    marginBottom: 14,
    marginTop: 8,
  },
  questionCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DDD5E5',
    borderRadius: 14,
    borderWidth: 1,
    padding: 18,
  },
  sectionTitle: {
    color: '#342E3A',
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 24,
  },
  divider: {
    backgroundColor: '#E7E0EB',
    height: 1,
    marginBottom: 18,
    marginTop: 12,
  },
  prompt: {
    color: '#342E3A',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
  },
  helper: {
    color: '#6A646E',
    fontSize: 13,
    fontStyle: 'italic',
    lineHeight: 19,
    marginTop: 4,
  },
  optionsScroll: {
    backgroundColor: '#FCF9FD',
    borderRadius: 8,
    height: 390,
    marginTop: 14,
  },
  options: {
    paddingHorizontal: 4,
  },
  option: {
    alignItems: 'center',
    borderBottomColor: '#EEE9F1',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 48,
    paddingHorizontal: 4,
  },
  optionPressed: {
    backgroundColor: '#F7F3FA',
  },
  checkbox: {
    alignItems: 'center',
    borderColor: '#756C7C',
    borderRadius: 3,
    borderWidth: 1.5,
    height: 20,
    justifyContent: 'center',
    marginLeft: 'auto',
    pointerEvents: 'none',
    width: 20,
  },
  checkboxSelected: {
    backgroundColor: '#6D50AC',
    borderColor: '#6D50AC',
  },
  checkmark: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 16,
  },
  optionText: {
    color: '#342E3A',
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    paddingRight: 16,
  },
  optionTextSelected: {
    color: '#57418D',
    fontWeight: '600',
  },
  actionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
  },
  stepBadge: {
    alignItems: 'center',
    borderColor: '#D8CEE1',
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    minWidth: 52,
    paddingHorizontal: 10,
  },
  stepText: {
    color: '#574F5D',
    fontSize: 13,
    fontWeight: '600',
  },
  recordButton: {
    alignItems: 'center',
    backgroundColor: '#6D50AC',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 112,
    paddingHorizontal: 18,
  },
  recordButtonDisabled: {
    backgroundColor: '#E7D8FF',
  },
  recordButtonPressed: {
    opacity: 0.82,
  },
  recordButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  recordButtonTextDisabled: {
    color: '#554766',
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(23, 21, 27, 0.42)',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    maxWidth: 420,
    padding: 22,
    width: '100%',
  },
  modalTitle: {
    color: '#17151B',
    fontSize: 18,
    fontWeight: '700',
  },
  modalInput: {
    backgroundColor: '#F1EDF4',
    borderBottomColor: '#5E5862',
    borderBottomWidth: 1,
    color: '#17151B',
    fontSize: 16,
    height: 52,
    marginTop: 20,
    paddingHorizontal: 14,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 20,
  },
  modalButton: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 76,
    paddingHorizontal: 12,
  },
  modalButtonPressed: {
    backgroundColor: '#F2EEF8',
  },
  modalButtonText: {
    color: '#57418D',
    fontSize: 14,
    fontWeight: '600',
  },
  modalButtonTextDisabled: {
    color: '#9A95A0',
  },
  intensityPromptRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 22,
  },
  intensityPrompt: {
    color: '#342E3A',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 28,
  },
  intensityInput: {
    borderBottomColor: '#6D50AC',
    borderBottomWidth: 2,
    color: '#57418D',
    fontSize: 19,
    fontWeight: '700',
    height: 40,
    marginHorizontal: 8,
    paddingHorizontal: 4,
    textAlign: 'center',
    width: 42,
  },
  slider: {
    height: 52,
    marginTop: 26,
    width: '100%',
  },
  scaleLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: -4,
  },
  scaleLabel: {
    color: '#6A646E',
    fontSize: 12,
  },
  painDescription: {
    color: '#342E3A',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
    marginTop: 26,
    minHeight: 44,
    textAlign: 'center',
  },
  summarySection: {
    borderBottomColor: '#EEE9F1',
    borderBottomWidth: 1,
    paddingVertical: 16,
  },
  summarySectionTitle: {
    color: '#342E3A',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
  },
  summaryPeriod: {
    color: '#342E3A',
    fontSize: 13,
    fontWeight: '700',
  },
  summaryText: {
    color: '#4F4B55',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
  },
  summaryItem: {
    color: '#4F4B55',
    fontSize: 14,
    lineHeight: 22,
    marginTop: 4,
  },
  summaryValue: {
    fontWeight: '700',
  },
  summaryFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  sessionNote: {
    color: '#6A646E',
    flex: 1,
    fontSize: 12,
    marginRight: 12,
  },
  summaryCloseButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D8CEE1',
    borderWidth: 1,
  },
  summaryCloseButtonText: {
    color: '#57418D',
  },
});
